export class Customer {
    Name: string;
    Name2: string;
    LangID: number;
    ID: number;
    CustomerNo: string;
    LockUpTitle: number;
    IndOrComp: number;
    CommName: string;
    PhoneCode: string;
    Phone: string;
    Mobile: string;
    Fax: string;
    Email: string;
    Website: string;
    Address: string;
    LockUpLanguage: number;
    LockUpSecotor: number;
    CityID: number;
    StatusDate: Date;
    LockUpGender: number;
    BirthDate: Date;
    ReferenceNo: string;
    RefEffectiveDate: Date;
    RefExpiryDate: Date;
    LockUpTaxType: number;
    TaxNo: string;
    StartDate: Date;
    Iban: string;
    BankID: number;
    BankBranchID: number;
    Status: number;
    StatusNotes: string;
    CreatedBy: string;
    CreationDate: Date;
    ModifiedBy: string;
    ModificationDate: Date;
    CompanyID: number;
    CurrencyCode: string;
    CountryCode: number;
    AreaID: number;
    PoBox: string;
    PostalCode: string;
    Nationality: number;
    IsVip: number;
    XCoordinates: string;
    YCoordinates: string;
    Logo: string;
    CustomerType: number;
<<<<<<< HEAD
    selected: boolean;
=======
    ShareType: number;
    AddUpdate: boolean;
>>>>>>> 66e265d62718c32628b39c593c4e0a2c24023f8b
}
